apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: gic2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  strategy: {}
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: registry.deti:5000/gic2/worker
          #imagePullPolicy: Never
          ports:
            - containerPort: 8001
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gic2-secret
                  key: password
          resources: {}
          volumeMounts:
            - name: dns-config-map
              mountPath: /etc/resolv.conf
              subPath: resolv.conf
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: dns-config-map
          configMap:
            name: dns-config-map
            items:
               - key: resolv.conf
                 path: resolv.conf
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: worker
      dnsPolicy: Default