apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: gic2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  strategy: {}
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: registry.deti:5000/gic2/worker
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          resources: {}
      #restartPolicy: Always
      #affinity:
      #  podAntiAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #    - topologyKey: kubernetes.io/hostname
      #      labelSelector:
      #        matchLabels:
      #          app: app