apiVersion: v1
kind: Service
metadata:
  namespace: gic2
  name: rabbitmq-cluster-service
  labels:
    app: rabbitmq
    type: LoadBalancer
spec:
  type: LoadBalancer
  ports:
   - name: http
     protocol: TCP
     port: 15672
   - name: prometheus
     protocol: TCP
     port: 15692
   - name: amqp
     protocol: TCP
     port: 5672
  selector:
    app: rabbitmq
