---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dailyenews-promo
  namespace: gic2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dailyenews-promo
  strategy: {}
  template:
    metadata:
      labels:
        app: dailyenews-promo
    spec:
      containers:
        - image: registry.deti:5000/gic2/dailynews-promo
          name: dailynews-promo
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always

# Create Service for Nginx
---
apiVersion: v1
kind: Service
metadata:
  name: dailyenews-promo
  namespace: gic2
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: dailyenews-promo

# Configure Traefik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dailyenews-promo
  namespace: gic2
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
    - host: dailynews-promo.k3s
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dailyenews-promo
                port:
                  number: 80
